### ISSUE TITLE
czboy想尝试utuntu做为开发环境

### ISSUE THREAD

**Issue by cz6oy** [dtboy1995/code-snippets#2]
czboy想尝试utuntu做为开发环境

**Comment by dtboy1995** [comment]
czboy你可以试试`优麒麟`或者`deepin`,直接使用Ubuntu反而配置上或者使用过程中包括中文支持需要花费很多时间去解决。

**Comment by dtboy1995** [comment]
> czboy想尝试utuntu做为开发环境

czboy你可以试试`优麒麟`或者`deepin`,直接使用Ubuntu反而配置上或者使用过程中包括中文支持需要花费很多时间去解决。

**Comment by cz6oy** [comment]
deepin使用过了，有点卡。虚拟机跑ubuntu也有点卡，不知道ubuntu作为开发是否合适，是否比windows效率高（主要是装 逼...）

**Comment by cz6oy** [comment]
> > czboy想尝试utuntu做为开发环境
> 
> czboy你可以试试`优麒麟`或者`deepin`,直接使用Ubuntu反而配置上或者使用过程中包括中文支持需要花费很多时间去解决。

**Comment by dtboy1995** [comment]
> deepin使用过了，有点卡。虚拟机跑ubuntu也有点卡，不知道ubuntu作为开发是否合适，是否比windows效率高（主要是装 逼...）

试试 优麒麟 或者直接上ubuntu16.04
